### PR TITLE
Fix race condition

### LINKED ISSUE #23: Race condition leading to deadlock in debounce trigger
When only using the debounce trigger and a muse is enqueued while a fetch is currently happening, the new timestamp is lost due to the `reset!` right after the fetch:
https://github.com/oliyh/superlifter/blob/d0baf9538f1dac712415323a2f2a6578c181bd97/src/superlifter/core.cljc#L159-L162
Provided no new muse will be added after the `reset!`, the added muse will never be fetched.

### PR DESCRIPTION
**Pull request by neominik**
Fixes #23

### CODE REVIEW

**Comment by oliyh** [comment]
Hello,

Thank you for reporting this. Would we not need the same check at https://github.com/oliyh/superlifter/pull/24/files#diff-53fa11e40c1e91d8226bb3a21d4ee41f1c4f14f02ea75e6c4e9e43b57301944aR142 ?

This is probably also a good usecase for `compare-and-set!` as well, do you think?

Thanks

**Comment by neominik** [comment]
> Would we not need the same check at https://github.com/oliyh/superlifter/pull/24/files#diff-53fa11e40c1e91d8226bb3a21d4ee41f1c4f14f02ea75e6c4e9e43b57301944aR142 ?

I think your reference might be broken. Could you clarify which other place you mean?

> This is probably also a good usecase for compare-and-set! as well, do you think?

Yes, this is actually be a cleaner solution. Will update the PR.

**Comment by oliyh** [comment]
Hi,

I meant for the cljs implementation, this line here: https://github.com/oliyh/superlifter/blob/master/src/superlifter/core.cljc#L142

Thanks

**Comment by neominik** [comment]
Sure, there you go. Since the cljs code is in its own function, I didn't see the duplication immediately. Thanks for pointing it out!

**Comment by oliyh** [comment]
Thanks for your contribution!

**Comment by oliyh** [comment]
Deployed to clojars as `0.1.4-SNAPSHOT`

**Pull request merged**
